function matrixGPU = BEMenerg_dir_launchKernelV(gpuID, kernel, deltaT, velP, velS, constFactor, ...
                                                        stdGHw, stdGHnx, stdGHny, stdGHnz, numNodiExt, ...
                                                        stdGHCw, stdGHCnx, stdGHCny, stdGHCnz, ...
                                                        vertsT, areeT, offSet, numBlocks, ...
                                                        numTriang, numBlocksPerIter, maxLen)
%Array di input
matrixGPU = zeros((3*numTriang)^2 * numBlocksPerIter, 1, 'gpuArray');
wait(gpuID);

%Avvio computazione GPU
matrixGPU = feval(kernel, matrixGPU, deltaT, velP, velS, constFactor, ...
                    stdGHw, stdGHnx, stdGHny, stdGHnz, numNodiExt, ...
                    stdGHCw, stdGHCnx, stdGHCny, stdGHCnz, ...
                    vertsT, areeT, offSet, numBlocks, maxLen);

return