function subBlockK = calcSingSubBlockK_c(pbParam, domainMesh, methodSpecs, constValuesCurr, G1Dn, G1Dw, indTemp, indM)
%CALCSINGSUBBLOCKK_C  Correct the self-triangle (singular) contribution of a K_c matrix block.
%   SUBBLOCKK = CALCSINGSUBBLOCKK_C(PBPARAM, DOMAINMESH, METHODSPECS, CONSTVALUESCURR, G1DN, G1DW, INDTEMP, INDM)
%   evaluates, for triangle INDM and discrete time-lag INDTEMP, the singular
%   self-interaction 3x3 sub-block of the triangle-collocated double-layer operator used
%   by CALCMATRIXK_C. The kernel is regularized (via GETKERNELSFUNCTIONHANDLES, a local
%   helper) into a closed-form "domain" part, integrated on the light-cone-intersected
%   sub-triangles via GENERATEFINALG2DNODES, plus a "boundary" line term integrated with
%   the trapezoidal rule along the triangle's three edges. Both are combined with a
%   third-order backward finite-difference in time (coefficients [-1, 3, -3, 1]).
%   The function returns early (an all-zero block) once the time-lag exceeds the light-cone
%   support implied by the triangle's largest edge length (DOMAINMESH.maxL).
%
%   Input arguments:
%       PBPARAM         - (struct) physical/time-discretization parameters (deltaT,
%                         velP, velS, lambda, mu, rho), see READINPUTFILE.
%       DOMAINMESH      - (struct) triangulated boundary mesh (normal,
%                         coordinates, triangles, maxL), see READSPACEMESH.
%       METHODSPECS     - (struct) quadrature scheme sizes, including numBOUND (points
%                         per edge for the boundary term), see GENERATEQUADDATA.
%       CONSTVALUESCURR - (struct) precomputed data for triangle INDM,
%                         one entry of CALCCONSTVALUES's output.
%       G1DN            - (double) 1D Gauss-Legendre nodes on [-1, 1].
%       G1DW            - (double) 1D Gauss-Legendre weights.
%       INDTEMP         - (nonnegative integer) discrete time-lag index for this block.
%       INDM            - (positive integer) index of the triangle.
%
%   Output arguments:
%       SUBBLOCKK - (3x3 double) singular correction to add on
%                   the diagonal of the triangle's self-block.
%
%   Notes:
%       The inner "domain" integration is marked "Temp MATLAB code" in the
%       source and loops point-by-point in plain MATLAB rather than
%       vectorizing, unlike the sibling CALCSINGSUBBLOCKK; it is noticeably
%       slower and looks like a candidate for a future MEX/GPU port.
%
%   See also CALCMATRIXK_C, CALCCONSTVALUES, GENERATEFINALG2DNODES
arguments (Input)
    pbParam         (1, 1) struct
    domainMesh      (1, 1) struct
    methodSpecs     (1, 1) struct
    constValuesCurr (1, 1) struct
    G1Dn            (1, :) double
    G1Dw            (1, :) double
    indTemp         (1, 1) double {mustBeInteger, mustBeNonnegative}
    indM            (1, 1) double {mustBeInteger, mustBePositive}
end

arguments (Output)
    subBlockK (3, 3) double
end

import eebem.utility.quadratureRules.*

subBlockK = zeros(3, 3);
coef = [-1, 3, -3, 1];
istTemp = indTemp + [-2, -1, 0, 1];

if(indTemp >= ceil(domainMesh.maxL(indM) / (pbParam.velS * pbParam.deltaT)) + 2)
    return;
end

[nuKL, nuKT, nuKsmRj] = getKernelsFunctionHandles(pbParam);

minDiffTemp = istTemp(1) * pbParam.deltaT;
normInt = domainMesh.normal(indM, :);

for indZeta = 1 : 4
    if (istTemp(indZeta) <= 0)
        continue
    end

    intgTot = zeros(3, 3);
    currT = istTemp(indZeta) * pbParam.deltaT;

    for indSRext = 1 : methodSpecs.numSRext
        for indGHext = 1 : methodSpecs.numGHext
            indEXTn = (indSRext-1) * methodSpecs.numGHext + indGHext;
            nodoExt = constValuesCurr.EXTn{indEXTn};
            pesoExt = constValuesCurr.EXTw{indGHext};

            intgIntSing = zeros(3);
        
            for indChild = 1 : 3
                rMin = max(pbParam.velS * minDiffTemp, 0);
                rInt = pbParam.velS * currT;
                rExt = pbParam.velP * currT;

                [G2DCn, G2DCw] = generateFinalG2Dnodes(constValuesCurr.childVerts{indEXTn, indChild}, rMin, rInt, rExt, G1Dn = G1Dn, G1Dw = G1Dw);
                
                % Temp MATLAB code
                for indDiag = 1 : length(G2DCw)                            
                    %Calcolo nodo e peso corrente
                    nodoInt = G2DCn(indDiag, :);
                    pesoInt = G2DCw(indDiag);
        
                    %Calcolo variabili
                    vettR = nodoExt - nodoInt;
                    lungR = norm(vettR, 2);
        
                    %Calcolo somma dei nuclei
                    somNucleiZeta = nuKL(vettR, lungR, normInt, currT) + nuKT(vettR, lungR, normInt, currT);
        
                    %Aggiornamento valore singolo integrale interno
                    intgIntSing = intgIntSing + pesoInt .* somNucleiZeta;
                end
            end

            
            %Cicli per termine di bordo (integro con trapezi)
            intgBoundSing = zeros(3);
            vertsInt = domainMesh.coordinates(domainMesh.triangles(indM, 1:3), :);
            latiInt = {vertsInt(2, :) - vertsInt(1, :), vertsInt(3, :) - vertsInt(2, :), vertsInt(1, :) - vertsInt(3, :)};
            for indL = 1 : 3
                points = vertsInt(indL, :) + linspace(0, 1, methodSpecs.numBOUND + 1)' .* latiInt{indL};
                vettTang = latiInt{indL} ./ norm(latiInt{indL}, 2);
                for indS = 1 : methodSpecs.numBOUND
                    vettR = nodoExt - points(indS, :);
                    lungR = norm(vettR, 2);
                    valStart = nuKsmRj(vettR, lungR, currT, 1) .* vettTang(1) + nuKsmRj(vettR, lungR, currT, 2) .* vettTang(2) + nuKsmRj(vettR, lungR, currT, 3) .* vettTang(3);
        
                    vettR = nodoExt - points(indS+1, :);
                    lungR = norm(vettR, 2);
                    valEnd = nuKsmRj(vettR, lungR, currT, 1) .* vettTang(1) + nuKsmRj(vettR, lungR, currT, 2) .* vettTang(2) + nuKsmRj(vettR, lungR, currT, 3) .* vettTang(3);
        
                    intgBoundSing = intgBoundSing + ((valStart + valEnd) .* norm(points(indS+1, :) - points(indS, :), 2) ./ 2);
                end
            end
            %Somma pesata contributi
            intgTot = intgTot + pesoExt .* (intgIntSing + intgBoundSing);
        end
    end

    subBlockK = subBlockK + coef(indZeta) .* intgTot;
end

subBlockK = subBlockK ./ (4 * pi * pbParam.deltaT);
end


function [nuKL, nuKT, nuKsmRj] = getKernelsFunctionHandles(pbParam)
%Build closed-form kernel handles (domain "L"/"T" parts and boundary
%line term "smRj") for the regularized double-layer collocated kernel.

%Parametri del problema
lambda = pbParam.lambda;
mu = pbParam.mu;
rho = pbParam.rho;

cP = pbParam.velP;
cS = pbParam.velS;

%Tensore di permutazione
tensorE = zeros(3, 3, 3);
tensorE(1, 2, 3) = 1;
tensorE(2, 3, 1) = 1;
tensorE(3, 1, 2) = 1;
tensorE(3, 2, 1) = -1;
tensorE(2, 1, 3) = -1;
tensorE(1, 3, 2) = -1;

nuKL = @(Vr, Lr, Vn, DeltaT) [(lambda/(lambda + mu)) * Vr(1) * Vn(1) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) * Vr(1) * Vn(1) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)), ...
                              (lambda/(lambda + mu)) * Vr(1)*Vn(2) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) * Vr(2) * Vn(1) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)), ...
                              (lambda/(lambda + mu)) * Vr(1) * Vn(3) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) * Vr(3) * Vn(1) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)); ...
                              (lambda/(lambda + mu)) * Vr(2) * Vn(1) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) * Vr(1) * Vn(2) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)), ...
                              (lambda/(lambda + mu)) * Vr(2) * Vn(2) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) * Vr(2) * Vn(2) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)), ...
                              (lambda/(lambda + mu)) * Vr(2) * Vn(3) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) * Vr(3) * Vn(2) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)); ...
                              (lambda/(lambda + mu)) * Vr(3) * Vn(1) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) * Vr(1) * Vn(3) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)), ...
                              (lambda/(lambda + mu)) * Vr(3) * Vn(2) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)) ...
                                        + (mu / (lambda + mu)) *  Vr(2) * Vn(3) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0)), ...
                              (lambda/(lambda + mu)) * Vr(3) * Vn(3) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0))  ...
                                        + (mu / (lambda + mu)) *  Vr(3) * Vn(3) / (Lr^3) * ((DeltaT - (Lr/cP)) * ((DeltaT - (Lr/cP)) > 0) - (DeltaT - (Lr/cS)) * ((DeltaT - (Lr/cS)) > 0))];

nuKT = @(Vr, Lr, Vn, DeltaT) [(lambda/(lambda + mu)) * Vr(1) * Vn(1) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) * Vr(1) * Vn(1) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)), ...
                              (lambda/(lambda + mu)) * Vr(1) * Vn(2) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) * Vr(2) * Vn(1) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)), ...
                              (lambda/(lambda + mu)) * Vr(1) * Vn(3) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) * Vr(3) * Vn(1) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)); ...
                              (lambda/(lambda + mu)) * Vr(2) * Vn(1) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) * Vr(1) * Vn(2) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)), ...
                              (lambda/(lambda + mu)) * Vr(2) * Vn(2) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) * Vr(2) * Vn(2) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)), ...
                              (lambda/(lambda + mu)) * Vr(2) * Vn(3) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) * Vr(3) * Vn(2) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)); ...
                              (lambda/(lambda + mu)) * Vr(3) * Vn(1) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) * Vr(1) * Vn(3) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)), ...
                              (lambda/(lambda + mu)) * Vr(3) * Vn(2) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)) ...
                                        + (mu / (lambda + mu)) *  Vr(2) * Vn(3) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS)), ...
                              (lambda/(lambda + mu)) * Vr(3) * Vn(3) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS))  ...
                                        + (mu / (lambda + mu)) *  Vr(3) * Vn(3) / (Lr^2) * ((((DeltaT - (Lr/cP)) > 0) / cP) - (((DeltaT - (Lr/cS)) > 0) / cS))];

nuKsmRj = @(Vr, Lr, DeltaT, j) [(2 * mu / rho) .* (tensorE(j, 1, 2) .* (3 .* Vr(2) .* Vr(1) ./ (Lr^5)) + tensorE(j, 1, 3) .* (3 .* Vr(3) .* Vr(1) ./ (Lr^5))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 1, 2) .* (Vr(2) .* Vr(1) ./ (Lr^3)) + tensorE(j, 1, 3) .* (Vr(3) .* Vr(1) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))), ...
                                (lambda * mu / (rho * (lambda+mu))) .* tensorE(j, 2, 1) ./ Lr .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))) ...
                                                + (2 * mu / rho) .* (tensorE(j, 1, 2) .* (3 .* Vr(2) .* Vr(2) ./ (Lr^5) - 1 ./ (Lr^3)) + tensorE(j, 1, 3) .* (3 .* Vr(3) .* Vr(2) ./ (Lr^5))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 1, 2) .* (Vr(2) .* Vr(2) ./ (Lr^3)) + tensorE(j, 1, 3) .* (Vr(3) .* Vr(2) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))), ...
                                (lambda * mu / (rho * (lambda+mu))) .* tensorE(j, 3, 1) ./ Lr .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))) ...
                                                + (2 * mu / rho) .* (tensorE(j, 1, 2) .* (3 .* Vr(2) .* Vr(3) ./ (Lr^5)) + tensorE(j, 1, 3) .* (3 .* Vr(3) .* Vr(3) ./ (Lr^5) - 1 ./ (Lr^3))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 1, 2) .* (Vr(2) .* Vr(3) ./ (Lr^3)) + tensorE(j, 1, 3) .* (Vr(3) .* Vr(3) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))); ...
                                (lambda * mu / (rho * (lambda+mu))) .* tensorE(j, 1, 2) ./ Lr .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))) ...
                                                + (2 * mu / rho) .* (tensorE(j, 2, 1) .* (3 .* Vr(1) .* Vr(1) ./ (Lr^5) - 1 ./ (Lr^3)) + tensorE(j, 2, 3) .* (3 .* Vr(3) .* Vr(1) ./ (Lr^5))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 2, 1) .* (Vr(1) .* Vr(1) ./ (Lr^3)) + tensorE(j, 2, 3) .* (Vr(3) .* Vr(1) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))), ...
                                (2 * mu / rho) .* (tensorE(j, 2, 1) .* (3 .* Vr(1) .* Vr(2) ./ (Lr^5)) + tensorE(j, 2, 3) .* (3 .* Vr(3) .* Vr(2) ./ (Lr^5))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 2, 1) .* (Vr(1) .* Vr(2) ./ (Lr^3)) + tensorE(j, 2, 3) .* (Vr(3) .* Vr(2) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))), ...
                                (lambda * mu / (rho * (lambda+mu))) .* tensorE(j, 3, 2) ./ Lr .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))) ...
                                                + (2 * mu / rho) .* (tensorE(j, 2, 1) .* (3 .* Vr(1) .* Vr(3) ./ (Lr^5)) + tensorE(j, 2, 3) .* (3 .* Vr(3) .* Vr(3) ./ (Lr^5) - 1 ./ (Lr^3))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 2, 1) .* (Vr(1) .* Vr(3) ./ (Lr^3)) + tensorE(j, 2, 3) .* (Vr(3) .* Vr(3) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))); ...
                                (lambda * mu / (rho * (lambda+mu))) .* tensorE(j, 1, 3) ./ Lr .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))) ...
                                                + (2 * mu / rho) .* (tensorE(j, 3, 1) .* (3 .* Vr(1) .* Vr(1) ./ (Lr^5) - 1 ./ (Lr^3)) + tensorE(j, 3, 2) .* (3 .* Vr(2) .* Vr(1) ./ (Lr^5))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 3, 1) .* (Vr(1) .* Vr(1) ./ (Lr^3)) + tensorE(j, 3, 2) .* (Vr(2) .* Vr(1) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))), ...
                                (lambda * mu / (rho * (lambda+mu))) .* tensorE(j, 2, 3) ./ Lr .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))) ...
                                                + (2 * mu / rho) .* (tensorE(j, 3, 1) .* (3 .* Vr(1) .* Vr(2) ./ (Lr^5)) + tensorE(j, 3, 2) .* (3 .* Vr(2) .* Vr(2) ./ (Lr^5) - 1 ./ (Lr^3))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 3, 1) .* (Vr(1) .* Vr(2) ./ (Lr^3)) + tensorE(j, 3, 2) .* (Vr(2) .* Vr(2) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))), ...
                                (2 * mu / rho) .* (tensorE(j, 3, 1) .* (3 .* Vr(1) .* Vr(3) ./ (Lr^5)) + tensorE(j, 3, 2) .* (3 .* Vr(2) .* Vr(3) ./ (Lr^5))) ...
                                                                            .* ((DeltaT - (Lr/cS))^2 .* (DeltaT + 2.*(Lr/cS)) ./ 6 .* ((DeltaT - (Lr/cS)) > 0) - (DeltaT - (Lr/cP))^2 .* (DeltaT + 2.*(Lr/cP)) ./ 6 .* ((DeltaT - (Lr/cP)) > 0)) ...
                                                + (2 * mu / rho) .* (tensorE(j, 3, 1) .* (Vr(1) .* Vr(3) ./ (Lr^3)) + tensorE(j, 3, 2) .* (Vr(2) .* Vr(3) ./ (Lr^3))) ...
                                                                            .* (((DeltaT - (Lr/cS)) .* ((DeltaT - (Lr/cS)) > 0) / (cS^2)) - ((DeltaT - (Lr/cP)) .* ((DeltaT - (Lr/cP)) > 0) / (cP^2))) ...
                               ];

end