function matrixGPU = BEMenerg_dir_launchKernelK_uConstSpace(gpuID, kernel, deltaT, velP, velS, lambda, mu, rho, constFactor, ...
                                                        stdGHw, stdGHnx, stdGHny, stdGHnz, numNodiExt, ...
                                                        stdGHCw, stdGHCnx, stdGHCny, stdGHCnz, ...
                                                        vertsT, areeT, normT, offSet, numBlocks, numTriang, numBlocksPerIter, maxLen, matCoeff, vetCoeff)
%Array di input
matrixGPU = zeros((9*numTriang) * (9*numTriang) * numBlocksPerIter, 1, 'gpuArray');
wait(gpuID);

%Avvio computazione GPU
matrixGPU = feval(kernel, matrixGPU, deltaT, velP, velS, lambda, mu, rho, constFactor, ...
                    stdGHw, stdGHnx, stdGHny, stdGHnz, numNodiExt, ...
                    stdGHCw, stdGHCnx, stdGHCny, stdGHCnz, ...
                    vertsT, areeT, normT, offSet, numBlocks, maxLen, matCoeff, vetCoeff);

return