function matrixGPU = BEMenerg_coreFN_launchKernelK(gpuID, kernel, deltaT, velP, velS, lambda, mu, rho, constFactor, ...
                                                        stdGHw, stdGHnx, stdGHny, stdGHnz, numNodiExt, ...
                                                        stdGHCw, stdGHCnx, stdGHCny, stdGHCnz, ...
                                                        vertsT, areeT, normT, indSMmatrix, matCoeff, vetCoeff, ...
                                                        offSet, numBlocks, numTriang, numNodes, numBlocksPerIter, nodesMesh, maxLen)
%Array di input
matrixGPU = zeros((3*numTriang) * (9*numTriang) * numBlocksPerIter, 1, 'gpuArray');
wait(gpuID);

%Avvio computazione GPU
matrixGPU = feval(kernel, matrixGPU, deltaT, velP, velS, lambda, mu, rho, constFactor, ...
                    stdGHw, stdGHnx, stdGHny, stdGHnz, numNodiExt, ...
                    stdGHCw, stdGHCnx, stdGHCny, stdGHCnz, ...
                    vertsT, areeT, normT, indSMmatrix, matCoeff, vetCoeff, ...
                    offSet, numBlocks, nodesMesh, maxLen);

return